### PR TITLE
Addition of sub-IDOs to the sub-IDO class

### PR DESCRIPTION
**Pull request by Mttbnchtt**
I open this PR to carry out the task described in #151.

### CODE REVIEW

**Comment by Mttbnchtt** [comment]
@pbuttigieg and @marieALaporte: it looks like this PR has conflicts. However, I do not see any other open PR editing the same file. For now, I have only added on sub-IDO, just to get started with the PR. Should I continue or wait until we clarify the situation?

**Comment by marieALaporte** [comment]
It seems like the IDOs instances that you added yesterday are not in the file. Did you pull from master before branching?

**Comment by Mttbnchtt** [comment]
I see the IDOs from the master branch in Protege. Although both I and @pbuttigieg had to refresh or restart Protege a couple of times before seeing all of them. Not sure what this means.

**Comment by marieALaporte** [comment]
@Mttbnchtt yes, maybe the best will be to close this PR and start again, by pulling first the changes into master and then branching

**Comment by Mttbnchtt** [comment]
Indeed, I do not see the IDOs in the IDO class if I am in the issue-151 branch. I let you or @pbuttigieg close the branch to be sure that it is done correctly. Should I then re-add the first sub-IDO? (Good we spotted the issue early.)

**Comment by pbuttigieg** [comment]
Agreed with @marieALaporte 

It looks like your OWL is behind. Try syncing the repo again and then branching. Make sure you see what you expect to in the OWL, that you're on the right branch, and have the most recent version of master.

The conflicts themselves are trivial, so it's just a question of refreshing.

image

**Comment by Mttbnchtt** [comment]
@pbuttigieg: sorry but I am not sure what to do exactly. I have just refreshed my GH Desktop and Protege, but, in branch issue-151 I do not see all the IDOs. I see them in the master though. I am not sure how to see OWL code and what it is that I should expect there. I am also not sure which is the "right" branch at this point. I do have the newest version of the master branch.

**Comment by marieALaporte** [comment]
@Mttbnchtt the simplest is to start a new branch because even if you use the git command line and merge master into your branch, you will have to resolve conflicts. This is doable is you really want to do it.

**Comment by Mttbnchtt** [comment]
As suggested by @marieALaporte and @pbuttigieg, I close this PR. We will use PR #153 instead.

**Pull request closed without merging**
